#!/bin/sh

if [ `git status -s|wc -l` -gt '0' ]; then
  echo 'commit changes first'
  exit 1
fi

npm run lint || exit 1
npm test     || exit 1
cli=node_modules/.bin

babel() {
  ${cli}/babel $1 --out-dir ${2:-$1} || exit 1
}

babel component
babel decorator
babel lib
babel view

if [ "$1" = '--deploy' ]; then
  # npm publish --tag beta
  npm publish
  git reset HEAD --hard
fi
