#!/bin/sh

source .script/status

npm run lint || exit 1
npm test     || exit 1
cli=node_modules/.bin

babel() {
  ${cli}/babel $1 --out-dir ${2:-$1} || exit 1
}

prefixer() {
  for css in `find $1 -name '*.css'`
  do
    ${cli}/postcss --config .config/postcss.config.js --output "$css" "$css" || exit 1
  done
}

babel component
babel decorator
babel lib
babel view

prefixer style

if [ "$1" = '--deploy' ]; then
  # npm publish --tag beta
  npm publish
  git reset HEAD --hard
fi
