#!/bin/sh

# build the latest one
styleguidist --config .styleguidist/config.js build

# update latest preview
minorVersion=`sed -n '/version/p' package.json|cut -d'"' -f4|cut -d. -f1,2`
cp -r docs/$minorVersion/* docs/

# update index
available=`ls -d docs/*/|cut -f2 -d'/'|grep -v build|sed -E 's/(.*)/    <a href="\1\/index.html">\1<\/a>/'`

echo "<!doctype html>
<html>
  <head>
    <meta charset=\"utf-8\">
    <title>Available Versions / Teatime Components</title>
  </head>
  <body>
$available
  </body>
</html>" > docs/version.html
